### ISSUE TITLE
Python SDK not compatible with Pydantic 2.0

### ISSUE THREAD

**Issue by AvikantSrivastava** [langfuse/langfuse-python#147] opened 2023-10-25 07:38 UTC
```bash
poetry add langfuse           
```
```
The currently activated Python version 3.10.10 is not supported by the project (^3.11).
Trying to find and use a compatible version. 
Using python3 (3.11.0)
Using version ^1.1.2 for langfuse

Updating dependencies
Resolving dependencies... (0.7s)

Because no versions of pydantic-settings match >2.0.2,<2.0.3 || >2.0.3,<3.0.0
 and pydantic-settings (2.0.2) depends on pydantic (>=2.0.1), pydantic-settings (>=2.0.2,<2.0.3 || >2.0.3,<3.0.0) requires pydantic (>=2.0.1).
And because pydantic-settings (2.0.3) depends on pydantic (>=2.0.1), pydantic-settings (>=2.0.2,<3.0.0) requires pydantic (>=2.0.1).
Because no versions of langfuse match >1.1.2,<2.0.0
 and langfuse (1.1.2) depends on pydantic (>=1.10.7,<2.0), langfuse (>=1.1.2,<2.0.0) requires pydantic (>=1.10.7,<2.0).
Thus, langfuse (>=1.1.2,<2.0.0) is incompatible with pydantic-settings (>=2.0.2,<3.0.0).
So, because my-llm-app depends on both pydantic-settings (^2.0.2) and langfuse (^1.1.2), version solving failed.
```

**Comment by AvikantSrivastava** [comment] 2023-10-25 07:39
@marcklingen any plans for version upgrades?
I am more than happy to contribute to this issue

**Comment by maxdeichmann** [comment] 2023-10-25 10:00
@AvikantSrivastava thanks for raising this. It looks like you are having issues with Pydantic. We track this issue here already with some added context: https://github.com/langfuse/langfuse/issues/228

I also see that you have commented here: https://github.com/fern-api/fern-python/issues/288

I will try that out immediately to see whether this fixes our issue.

**Comment by maxdeichmann** [comment] 2023-10-25 10:01
Closing this as this is a duplicate

**Closed by maxdeichmann** 2023-10-25 10:01 UTC

**Comment by maxdeichmann** [comment] 2023-10-26 11:39
@AvikantSrivastava the issue is resolved by now
